### ISSUE TITLE
System setting sliders only retain position when you select Calibrate

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#11]
### Steps to reproduce

1. Enter the system settings
2. Adjust a slider
3. Click back
4. Enter system settings again to find slider position reset

### Suggested fix

Add save button or save when back button is clicked.

**Comment by aarontabor** [comment]
As far as I can tell, this has been fixed by David in 4a3f588428fb6ae305f2200c976671618631a8c3.
