### ISSUE TITLE
Green buttons don't work, must click text to trigger event

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#12]
### Steps to reproduce
1. click on the green part of any green button
2. click on the text part of any green button

**Comment by ThePenguin1140** [comment]
@David-Hanna are we still planning on replacing the buttons with sprites?

**Comment by AlexKienzle** [comment]
This issue appears to be resolved, closing.

**Comment by AlexKienzle** [comment]
This issue still persists on the calibrate button in System Settings, and on the Calibration screen.

**Comment by caarlsmith** [comment]
Should be fixed now

**Comment by AlexKienzle** [comment]
Looks good, closing.
