### ISSUE TITLE
Obstacles can spawn on holes

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#13]
![Obstacle on a platform gap](https://cloud.githubusercontent.com/assets/19151434/15435916/6c8b06ac-1e95-11e6-966e-589d68f2a7b9.png)

**Comment by aarontabor** [comment]
This can be fixes either by making the platform spawning more intelligent (as to avoid the hole), or by repeating the current spawning algorithm until a more appropriate spawn-position is found
