### ISSUE TITLE
Obstacles can spawn such that they block the path

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#16]
Sometimes platforms are so close together that an obstacle can prevent the player from jumping over it.

**Comment by AlexKienzle** [comment]
![obstaclespawnblocking](https://cloud.githubusercontent.com/assets/19151434/15436955/ae566f0e-1e9a-11e6-912f-cf5477a2b9b0.png)

Image of the issue.

**Comment by aarontabor** [comment]
I'm going to tweak the lower bound on the distance between platforms, and see if this resolves the issue.

**Comment by aarontabor** [comment]
Another flavor of this issue is that an obstacle can spawn directly below a gap, blocking the path that the player would otherwise drop through.

**Comment by aarontabor** [comment]
I've reduced the maximum possible height of an obstacle to avoid this issue in commit 15f71c2d53a5795733cd17c7636090824e32db84

**Comment by AlexKienzle** [comment]
Issue still persists:
![obstaclespawnblocking2](https://cloud.githubusercontent.com/assets/19151434/15512876/69765914-21b8-11e6-95eb-34497ec68d9e.png)

**Comment by aarontabor** [comment]
I've made them small enough that this cannot happen anymore in 00efde027aea976df9dc6add58e312112d308f30. However, I'm thinking that the obstacles might look too now in comparison to the rest of the game. Maybe we want to make the minimum height between platforms a little larger to allow for bigger obstacles?
