### ISSUE TITLE
Calibration: Calibration Menu is currently quite vague

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#2]
When the user calibrates their Myo, not much feedback is given about the current readings and whether or not they seem reasonable. The menu could be improved by showing the user some information about what is happening on during Calibration.

Ideally:
- [ ] game enters a new state when scanning for Myo Armband (currently freezes until the Myo-Processing call times-out).
- [ ] more specific error message during calibration failure (differentiate between "No Myo" vs. "No EMG activity" error messages).
- [ ] during calibration, give user some visual feedback to show that EMG activity is detected
- [ ] calibration profiles that persist along with other save data.

**Comment by aarontabor** [comment]
Not so sure about the 4th point (persistent calibration profile), as it contradicts the simplicity of not having to worry about any specific orientation of the Myo armband.

**Comment by aarontabor** [comment]
Point 1 ("scanning for myo...") will probably involve forking another thread, which attempts to instantiate an instance of a Myo, and fires an event when it either succeeds or fails.

**Comment by alex959595** [comment]
I added  right and left handed picture  that are shown when user should signal left and right.
