### ISSUE TITLE
"Invisible" narrow platforms

### ISSUE THREAD

**Issue by AlexKienzle** [hcilab/processing-games#25]
When two gaps spawn close together, it can sometimes result in a platform that is less than a pixel wide. The player can still collide with the platform, but cannot see it.

**Comment by ThePenguin1140** [comment]
Not fixed, I just found it again in the latest version of the dev branch

**Comment by AlexKienzle** [comment]
I haven't seen this issue occur in a while, it's probably fine now. Closing.
