### ISSUE TITLE
Add a question mark on the red button next to "Input" in System Settings menu

### ISSUE THREAD

**Issue by AlexKienzle** [hcilab/processing-games#28]
The button gives the player additional information about the "Max" and "Difference" options in the "Input" field. Normally, buttons like this include a question mark. Also, the red circle doesn't match the theme of the other menus and buttons, so if possible, use a black circle outline with a black question mark in the center (like the back buttons).

**Comment by AlexKienzle** [comment]
This issue has been resolved, closing.

**Comment by ThePenguin1140** [comment]
This looks like a duplicate of #20.
