### ISSUE TITLE
Sticky platforms can sometimes spawn such that they are very long with a low ceiling

### ISSUE THREAD

**Issue by AlexKienzle** [hcilab/processing-games#29]
This is fairly unbalanced because when this occurs, you must jump to move, but when you hit the low ceiling you bounce back down to the ground. If it is a long platform, this issue is magnified, as it can take quite a bit of time to get down to the next platform. This is not too big of a deal at lower levels, but can basically force a game-over around level 40+ when the platforms move faster.

![stickyplatform](https://cloud.githubusercontent.com/assets/19151434/15503597/0a45feb2-2191-11e6-93bc-269cd4dcbca3.png)

**Comment by AlexKienzle** [comment]
This is only an issue when using the Myo because sticky platforms prevent you from moving unless you have superhuman strength, which forces you to jump.

**Comment by aarontabor** [comment]
I've reduced the coefficient of friction for sticky platforms in commit d901e2ae22d65326438d6febf19733313637a5ac

**Comment by AlexKienzle** [comment]
Sticky platforms work better with Myo input now, closing issue.
