### ISSUE TITLE
Movement controls sometimes get "stuck" (reproducible with keyboard controls)

### ISSUE THREAD

**Issue by AlexKienzle** [hcilab/processing-games#33]
Steps to Reproduce:
1. Start game
2. Hold arrow key (left, up, or right)
3. Press space to pause while holding arrow key
4. Release arrow key
5. Click back button to return to game

When you follow these steps, Momo will act as though you are still holding the movement key. For example if you held the left key, Momo will fly/roll left. This can be cancelled by pressing the "stuck" direction key to trigger the release event.

**Comment by AlexKienzle** [comment]
Since this issue is related to keyboard controls, doesn't happen often, and has a workaround, it shouldn't be top priority.

**Comment by alex959595** [comment]
Does not happen anymore... Issue is fixed
