### ISSUE TITLE
Re-calibrate text larger than button on calibration screen

### ISSUE THREAD

**Issue by AlexKienzle** [hcilab/processing-games#35]
Once Myo is calibrated, the "Re-calib
![recalibratebutton](https://cloud.githubusercontent.com/assets/19151434/15516782/d2d284ca-21ca-11e6-9942-b84b0bb56c21.png)
rate" button will appear, but the sizing is off.

**Comment by caarlsmith** [comment]
Is this still happening?

**Comment by ThePenguin1140** [comment]
Well this needs to be fixed, but I don't think anybody is working on it.
