### ISSUE TITLE
Reorder options menu buttons

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#36]
Right now the order of the buttons seems odd. Might be worth to try to reorder them in a more intuitive way.

**Comment by caarlsmith** [comment]
Do you have a suggestion for the reordering?

**Comment by ThePenguin1140** [comment]
Hmm, we could talk about it during the stand-up but I was thinking for the options menu:
- Gameplay Record
- Customize!
- Game Settings
- System Settings
