### ISSUE TITLE
Gameplay: Coins spawn inside of obstacles and platforms

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#5]
Another polish situation. Sometimes coins spawn inside of the obstacles and platforms making it very hard/impossible to get them.

**Comment by ThePenguin1140** [comment]
See #9 for some images of the bugs.

**Comment by AlexKienzle** [comment]
![obstaclespawncoinblocking](https://cloud.githubusercontent.com/assets/19151434/15437263/98a3aea4-1e9c-11e6-8894-213098d413e8.png)

Similar issue, coin on left impossible to get because obstacle and wall are too close together. Also relates to issue #16.

**Comment by AlexKienzle** [comment]
Coins no longer spawn inside platforms. The issue still persists with obstacles.

**Comment by David-Hanna** [comment]
Increased the size of the hit box for coins to mitigate this issue. There may be a further improvement to solve this issue completely in the future. Worth taking another look to see if we can solve it algorithmically instead.
