### ISSUE TITLE
Minimum EMG input threshold should be configurable with a slider

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#54]
When a very small amplitude is read from an EMG sensor, we ignore the reading and interpret its value as 0 (essentially, we assume that the small amount of activity is unintentional). This helps to smooth the movement of Momo, since he stays stationary until the readings exceed a certain threshold.

Currently this threshold is configurable through XML, and the similar threshold for the first-over control policy is hard-coded.
# Proposed Solution

[ ] Thresholds for all three control policies should be controlled by the same variable
[ ] The threshold should be configurable from an options menu (probably close to the sensitivity slider) through the use of a slider.

**Comment by alex959595** [comment]
Is implemented in the game now in the system settings.
