### ISSUE TITLE
Display calibration debugging information during gameplay

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#56]
If it is possible to inconspiciously show sensor readings (I'm thinking in the same style that framerate is shown in videogame benchmarks; i.e., bottom corner, small font), it would be helpful for trouble shooting during gameplay.

I would make the presence of this output configurable from an xml parameter, but don't worry about an options menu setting.

**Comment by aarontabor** [comment]
Possible format for the info shown:

left: xx%, right: xx%

**Comment by aarontabor** [comment]
# Proposed Solution

- change numeric readings to some sort of visual representation (ex: an ascii-art bar that fills with strong contractions)
- provide a way to toggle the presence of this information during gameplay, either:
    - a hot key (ex: F1)
    - a setting in the pause menu

**Comment by alex959595** [comment]
This has now been taking care of with the Sensor Graph, activated when 'G' is pressed during game play.
