### ISSUE TITLE
Adaptive Difficulty: Momo's expression changes depending on player's location

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#60]
depends on #59 

To encourage the player to stay towards the bottom region of the screen when possible, we should modify Momo's sprite depending on which region he is currently in. For example, Momo could have a bead of sweat on his forehead when he is in the Danger Zone (since he is close to the spikes, and nervous), and could similarly be wearing a pair of sunglasses when he is in the Happy Zone (since everything is cool).

The exact expressions to give Momo are open for discussion.

**Comment by alex959595** [comment]
All characters now have expressions depending on what part of the screen they are currently on.
