### ISSUE TITLE
More coins should appear on lower levels

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#61]
Since the platforms move so slowly on the lower levels, the game may quickly become boring for those already skilled with Myo armband controls. Spawning more coins on these levels could keep them engaged.

**Comment by aarontabor** [comment]
A valid argument against this issue is that these players should just simply start at a higher level.  Our adaptive difficulty feature (#59) may make this a non-issue.

**Comment by alex959595** [comment]
More coins have now been added to lower levels.
