### ISSUE TITLE
Incorrect default customize setting when logging in with user profile.

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#64]
When logging in with a user profile (as opposed to playing in guest mode), the default customization options do not correspond to the first column on the customize menu.

For example, when I create a new user profile and then begin play, the game is configured with different settings (even though some of these items are locked):
- Regular Momo
- Motherload song
- Castle background
- Star "coins"

If I go into the Customize menu, and explicitly click on all items in the first column (the generic Momo theme), then the game appears as expected.

# Proposed Solution
I believe this is simply being caused because the inappropriate default values. Tweaking these should solve this issue.

**Comment by alex959595** [comment]
Updated the new theme which updated the indexes on the Customization defaults this happened in the reset() method in Customization Options. The proper defaults for Momo should now work.
