### ISSUE TITLE
ArrayIndexOutOfBounds exception selecting Kitty theme when logged in with player profile.

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#65]
When logged in with a user profile (as opposed to playing in guest mode), when I attempt to buy the Kitty themed background (`pretty.svg`) and song (`TheSky.wav`) the game crashes with an ArrayIndexOutOfBounds exception.

In commit bea216f4e9d5f6ac9dcd93d5f619a22f36cfd020 (branch `presentation`), I've fixed this issue for one specific player profile by adding a reference to these two files in the player's settings file, but this fixed should be applied globally so that it will fix the issue for all newly created player profiles.

# Proposed Solution
Modify the default `save_data` file that player profile's derive from, so that all newly created player profiles will reference the Kitty themed files.

**Comment by alex959595** [comment]
Updated the default_save_data to contain all the needed code and indexes for the newer themes.
