### ISSUE TITLE
All Calibration settings should be logged

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#69]
Currently, the most recent calibration setting (i.e., sensor ids, sensitivities, and control policy) is saved to the file `data/csv/calibration.csv`. This feature should be extended so that:
- separate calibration data is saved for each user login ID.
- a history of all previous calibrations is maintained

This can be accomplished by simply saving each calibration to a new, uniquely named file (I propose the naming convention `data/csv/<loginID>-<timestamp>-calibration.csv`), and then loading the most recent one (according to the timestamp) whenever the program is started or someone logs in.

**Comment by aarontabor** [comment]
The motivation for this feature is so that we can track a user's calibration settings over time. Wendy mentions that one of the beneficial ways she can see the game being used is to build strength in a patients muscles even before they receive a prosthesis, so that she doesn't have to send them home with high sensitivity settings on their new prosthesis (which leads to noisy control).

According to this, we should see the player's calibration sensitivities decrease over time.

**Comment by aarontabor** [comment]
Just looking through the code, and I think I'm going to take an approach similar to the `save_data` files instead:

- a calibration data file will be created for each user (`data/csv/calibration-<loginID>.csv`)
- add a new `timestamp` column to the table
- every recalibration/adjustment will create a new row in this table
- last row of the table is treated as current calibration settings

**Comment by alex959595** [comment]
Currently working on development branch so..
- calibration data file will be created for each user (data/csv/calibration-<loginID>.csv), guest is (calibration.csv)
- Every recalibration will create a new row in this table
- Every adjustment on the sliders will create a new row in this table when you leave the  gamestate (GameState_CalibrateSuccess)
- last row of the table is treated as current calibration settings
