### ISSUE TITLE
Provide a visual cue to the user during armband connect.

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#77]
It takes a couple of seconds to establish a bluetooth LE connection with the Myo armband. During this time (which happens immediately after clicking either the "left" or "right" forearm button in the calibration wizard), the game simply hangs and provides no feedback to the user that something is happening.

# Proposed solution

- [ ] change the cursor to a "Throbber" animation (spinning wheel) during this time.

**Comment by aarontabor** [comment]
Is the icon we want one of these?

https://processing.org/reference/cursor_.html

**Comment by scottbateman** [comment]
I think we want something like this: http://www.stikes-aisyiyah.ac.id/daftar/media/public/img/loaders/loading4.gif

Here is an example of creating image based animations:
https://processing.org/examples/animatedsprite.html

**Comment by aarontabor** [comment]
To make the cursor display as a throbber, use the following line:

`cursor(WAIT);`
