### ISSUE TITLE
Help and Credits

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#8]
Write up the credits and help for the game.

**Comment by AlexKienzle** [comment]
The credits look good, although Scott mentioned we should add Erik Scheme as a "Special Thanks". I am also assuming the appropriate assets have been credited, can @alex959595 confirm these?

**Comment by aarontabor** [comment]
I'm going to add Erik's name into the Credits screen. 

@alex959595 can you confirm that all sprite-related assets are present?

**Comment by aarontabor** [comment]
Commit 6a132c1102fc387787449c5da33a79b0ecacb72d adds Erik's name to the credits.

**Comment by alex959595** [comment]
@aarontabor  Yes all are present
