### ISSUE TITLE
Testing and Balacing

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#9]
Test the game and report any found bugs to the dev team. Ideally all new bugs will have an issue created on Github describing the bug and how to reproduce it.

# Testing Checklist: 

## General:
- [x] Window modes
- [ ] Sound

## Menus: 
- [x] General Navigation
- [x] EMG Calibration
- [ ] Sensitivity
- [ ] Stats
- [x] Buttons
- [ ] Sliders
- [ ] Other Options

## Game:
- [x] Gameplay
- [x] Jumping
- [x] Moving
- [x] Difficulty
- [x] Control Feel
- [x] Platform Types
- [x] Obstacles
- [x] Score
- [x] Spike Wall
- [x] Coins
- [x] Sprites
- [x] Input

# Possible Issues (Most of these may not have been implemented yet):

We'll list any problems we find here, once they are confirmed they'll be replaced with an issue.

1. ~~Coins could randomly spawn inside obstacles, platforms, or on other coins~~ #5 
2. System Settings sliders do not work
- ~~System Settings sliders only retain position when in-game when you select "Calibrate"~~ #11
- Clear button inactive
- Gameplay Record does not update
- ~~Green buttons don't work, need to click text object~~ #12 
- ~~Obstacle can spawn on holes~~ #13
- ~~Obstacles can spawn such that they block the only path~~ #16
- ~~Escape closes application entirely~~ #14
- ~~Invisible narrow platforms~~ #25 

These last 4 are were all moved to #15
- ~~Resizing game window too small (vertically) causes game to crash~~
- ~~Resizing game window causes collision detection and object visibility issues~~
- ~~On the calibration screen, when in fullscreen mode, colon overlaps with "T" in "RIGHT" and "LEFT"~~
- ~~On the Game Settings screen, when in fullscreen mode, letters in "Terrain" are overlapping~~
- ~~In fullscreen mode, player accelerates faster~~

# Improvements:
- ~~Add sound when adjusting audio settings~~ #17   
- ~~Allow keyboard shortcut (space) to unpause game~~ #18 
- ~~Death ceiling triggers before you reach it~~ #19
- Add highlight or animation on buttons on mouseover or click

**Comment by AlexKienzle** [comment]
![coinspawnobstacle](https://cloud.githubusercontent.com/assets/19151434/15435913/6c7e17c6-1e95-11e6-85cb-c3edcc56aba2.png)
![coinspawnoverlap](https://cloud.githubusercontent.com/assets/19151434/15435915/6c808e70-1e95-11e6-87a7-dd946cf47ff2.png)
![coinspawnplatform](https://cloud.githubusercontent.com/assets/19151434/15435914/6c7eadf8-1e95-11e6-9bc6-8c701347da24.png)
![obstaclespawnplatform](https://cloud.githubusercontent.com/assets/19151434/15435916/6c8b06ac-1e95-11e6-966e-589d68f2a7b9.png)

**Comment by ThePenguin1140** [comment]
Picture 1 looks like it belongs to #5 
![Coin spawns inside of obstacle](https://cloud.githubusercontent.com/assets/19151434/15435913/6c7e17c6-1e95-11e6-85cb-c3edcc56aba2.png)

**Comment by ThePenguin1140** [comment]
@AlexKienzle Do you think it would be alright for us to remove the list of problems we find from this issue? 
Since we've now gotten into the habit of making new issues for problems we find directly I don't see the point of having a duplicate list of stuff here.

**Comment by AlexKienzle** [comment]
@ThePenguin1140 Yeah, kill it.
